DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/symbols.sh


echo "Git Symbols:"
echo "${_violet}${is_a_git_repo_symbol}${_reset}  within a Git repo"
echo "${_yellow}${has_stashes_symbol}${_reset}  stashes present"
echo "${_red}${has_untracked_files_symbol}${_reset}  untracked files"
echo "${_yellow}${has_adds_symbol}${_reset}  new files staged"
echo "${_red}${has_deletions_symbol}${_reset}  deletions"
echo "${_yellow}${has_deletions_cached_symbol}${_reset}  deletions staged"
echo "${_red}${has_modifications_symbol}${_reset}  modifications"
echo "${_yellow}${has_modifications_cached_symbol}${_reset}  modifications staged"
echo "${_green}${ready_to_commit_symbol}${_reset}  ready to commit"
echo "${_red}${detached_symbol}${_reset}  detached head"
echo "${_red}${no_upstream_symbol}${_reset}  no upstream"
echo "${_yellow}${is_on_a_tag_symbol}${_reset}  on a tag"
echo "${needs_to_merge_symbol}${_reset} needs merge"
echo "${can_fast_forward_symbol}${_reset}  can fast forward"
echo "${has_diverged_symbol}${_reset}  has diverged"
echo "${rebase_tracking_branch_symbol}${_reset}  will rebase tracking branch"
echo "${merge_tracking_branch_symbol}${_reset} will merge tracking branch"
echo "${should_push_symbol}${_reset}  should push"
