# Symbols
: ${is_a_git_repo_symbol='♪'}
: ${has_stashes_symbol='◈'}
: ${has_untracked_files_symbol='╋'}
: ${has_adds_symbol='╋'}
: ${has_deletions_symbol='✕'}
: ${has_deletions_cached_symbol='✕'}
: ${has_modifications_symbol='●'}
: ${has_modifications_cached_symbol='●'}
: ${ready_to_commit_symbol='★'}
: ${detached_symbol='☢'}
: ${no_upstream_symbol='⇞'}
: ${is_on_a_tag_symbol='⌦'}
: ${needs_to_merge_symbol='ᄉ'}
: ${can_fast_forward_symbol='⇉'}
: ${has_diverged_symbol='Ⴤ'}
: ${rebase_tracking_branch_symbol='↸'}
: ${merge_tracking_branch_symbol='ᄉ'}
: ${should_push_symbol='↑'}


# Colors
: ${_on="\033[1;37m"}
: ${_off="\033[0m"}
: ${_red="\033[0;31m"}
: ${_green="\033[0;32m"}
: ${_yellow="\033[1;33m"}
: ${_violet="\033[0;35m"}
: ${_branch_color="\033[1;34m"}
: ${_reset="\033[0m"}

: ${on="\[${_on}\]"}
: ${off="\[${_off}\]"}
: ${red="\[${_red}\]"}
: ${green="\[${_green}\]"}
: ${yellow="\[${_yellow}\]"}
: ${violet="\[${_violet}\]"}
: ${branch_color="\[${_branch_color}\]"}
: ${reset="\[${_reset}\]"}
