# Symbols
: ${is_a_git_repo_symbol='♪'}
: ${has_stashes_symbol='◈'}
: ${has_untracked_files_symbol='╋'}
: ${has_adds_symbol='╋'}
: ${has_deletions_symbol='✕'}
: ${has_deletions_cached_symbol='✕'}
: ${has_modifications_symbol='●'}
: ${has_modifications_cached_symbol='●'}
: ${ready_to_commit_symbol='★'}
: ${detached_symbol='☢'}
: ${no_upstream_symbol='⇞'}
: ${is_on_a_tag_symbol='⌦'}
: ${needs_to_merge_symbol='ᄉ'}
: ${can_fast_forward_symbol='⇉'}
: ${has_diverged_symbol='Ⴤ'}
: ${rebase_tracking_branch_symbol='↸'}
: ${merge_tracking_branch_symbol='ᄉ'}
: ${should_push_symbol='↑'}

# Colors
: ${on="\[\033[1;37m\]"}
: ${off="\[\033[0m\]"}
: ${red="\[\033[0;31m\]"}
: ${green="\[\033[0;32m\]"}
: ${yellow="\[\033[1;33m\]"}
: ${violet="\[\033[0;35m\]"}
: ${branch_color="\[\033[1;34m\]"}
: ${reset="\[\033[0m\]"}
